### ISSUE TITLE
Bug report - CMake doesn't work in Debian

### ISSUE THREAD

**Issue by d3fault** [CypherpunkArmory/UserLAnd#1024]
# Describe the bug

When running CMake on a Hello World C++ app, I get the following error:

> cmake: error while loading shared libraries: /usr/lib/aarch64-linux-gnu/libc.so: invalid ELF header

Note: I was able to compile the very same Hello World C++ app by invoking g++ directly.

# Steps to reproduce the behavior:

0) Install Xfce via Userland
1) apt install cmake build-essential
2) Make a C++ Hello World app and CMakeList.txt file like described [here](http://derekmolloy.ie/hello-world-introductions-to-cmake/)
3) mkdir build && cd build && cmake ..
4) observe error stated above

# Screenshots

Too lazy for screenshot

# Device Information

Device: Moto X4 Android One Edition (Google Fi).
Android Version: Pie 9 Build number: PPWS29.69-39-2-4. Kernel version: 4.4.153-perf-gf156a67
UserLAnd Version: 2.6.2.
Whether the device is rooted: no
Whether the device is running LineageOS: no

**Comment by d3fault** [comment]
Sorry this was just a result of a crashed "apt dist-upgrade" (do want buster :-P). I tried again with a fresh Stretch installation and CMake works fine.

**Comment by mnh48** [comment]
can anyone help me, this is the only issue that mentioned about the same error
I get this error on pretty much most of stuff and idk how to fix it
`error while loading shared libraries: /usr/lib/aarch64-linux-gnu/libc.so: invalid ELF header`

I didn't do any dist upgrade, it just happened all of sudden
I can't use many programs because of it, wget, curl, cmake, remmina, etc
because of this I stuck with using precompiled binary programs
like when I need to wget something, I had to open firefox and download from there

### Device Information
Device: Samsung Galaxy S7 Edge (SM-G935F)
Android Version: 8.0.0 (Oreo)
UserLAnd Version: 2.7.2
Whether the device is rooted: no (and impossible to root - I don't have any desktop / PC / laptop after my only laptop unable to boot anymore after 6 years using it)
Whether the device is running LineageOS: no

Additional information from neofetch
OS: Ubuntu 18.04.4 LTS aarch64 
Host: Samsung UNIVERSAL8890 board based on EXYNOS8890 
Shell: bash 4.4.20 
DE: Xfce 
WM: Xfwm4 
WM Theme: Numix 
Theme: Adwaita-dark [GTK2/3] 
Icons: Elementary-xfce-darkest [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: (6) @ 1.586GHz 
Memory: 2933MiB / 3537MiB

**Comment by tomash** [comment]
Confirming same issue. Xperia XZ2 Compact, UserLand with Ubuntu 18.04. At first I was getting error with not found libdl:
```
tomek@localhost:~$ wget https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.bz2
wget: error while loading shared libraries: libdl.so: cannot open shared object file: No such file or directory
```

So I did `apt install build-essential`, it all went fine (despite a few warnings from update-alternatives) but now wget and curl (for example) throw libc ELF header error:
```
tomek@localhost:~$ wget
wget: error while loading shared libraries: /usr/lib/aarch64-linux-gnu/libc.so: invalid ELF header
tomek@localhost:~$ curl
curl: error while loading shared libraries: /usr/lib/aarch64-linux-gnu/libc.so: invalid ELF header
```
