### ISSUE TITLE
Bug report - [Cannot install a Desktop package -> E: Sub-process /usr/bin/dpkg returned an error code (1)]

### ISSUE THREAD

**Issue by Enzycal** [CypherpunkArmory/UserLAnd#1072]
# Describe the bug

The problem occurs after starting VNC.

After attempting to install a desktop package it fails returing an error.

> Setting up pavucontrol (3.0-4) ...  
> Setting up xfdesktop4 (4.12.4-2) ...  
> Setting up thunar (1.8.4-1) ...  
> Setting up xfce4-session (4.12.1-6) ...  
> update-alternatives: using /usr/bin/startxfce4 to provide /usr/bin/x-session-man alter (x-session-manager) in auto mode
> Setting up thunar-volman (0.9.1-1) ...
> Processing triggers for menu (2.1.47+b1) ...
> Processing triggers for initramfs-tools (0.133+deb1Oul) ...
> Processing triggers for libc-bin (2,28-10) ...
> Setting up xfce4 (4.12.5) ...
> Processing triggers for systemd (241-7"deb10u1) ...
> Setting up xorg (1:7.7+19) ...
> Processing triggers for dbus (1.12.16-1) ...
> Processing triggers for libgdk-pixbuf2.0-0:arm64 (2.38.1+dfsg-1) ...
> Errors were encountered while processing:
>    udisks2
>    gvfs-daemons
>    gvfs:arm64
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> An error occurred installing packages, please try again and if it persists provi de this log to the developer, I Press any key to close... 

# Steps to reproduce the behavior:

> From the main menu select Distribution -> Debian or Ubuntu, enter the info and start VNC. In the open terminal type to install a desktop package (lxde, xfce, mate): sudo apt-get install lxde

or

> From the main menu select Desktop-> Xfce, enter the info and start VNC. the installation automatically starts.

# Screenshots

https://imgur.com/a/iNmu3Qi

When selecting Desktop -> lxde: https://imgur.com/a/2gM1iez

# Device Information

Device: Samsung Galaxy Note 10+ 512Gb
Android Version: 9
UserLAnd Version 2.6.4
Device is NOT rooted.
Running stock ROM.

**Comment by valadina223** [comment]
Installing XFCE worked for me today. But instead LXDE does not work today. Have you tried again?

**Comment by Enzycal** [comment]
Just tried both, still doesn't work.

**Comment by valadina223** [comment]
Hm, strange. Worked for me yesterday. Seems the installation routine is really fragile.
If you don't get it to work at all, maybe you want to have a look at AnLinux. They basically do they same, offering XFCE, LXDE, LXQT. Tried all of them yesterday, works without any hassle.

**Comment by corbinlc** [comment]
Issue relates to `udisk2.postinst` doing this `udevadm trigger --subsystem-match=block --action=change`.  Looking at this now.

**Comment by corbinlc** [comment]
Ok.  Simply clicking on the xfce or lxde icons now works (may require a setting up a new filesystem if already broken).  If people want to install a desktop on their own and they run into the same problem with udisks2, the workaround I ultimately used is...
instead of just doing something like this:
`sudo apt install xfce4`
the scripts now do something like this:
```
sudo apt install udisks2
sudo rm /var/lib/dpkg/info/udisks2.postinst
sudo dpkg --configure udisks2
sudo apt install xfce4
```
This issue has been fixed in later version of the `udev` package where the issue really resides, and so this workaround can be removed later when those packages become part of `stable`.

So, one way or another, you should be able to proceed now.  Enjoy!

Some references:
Example commit that fixes this: 
https://github.com/CypherpunkArmory/UserLAnd-Assets-Support/commit/f6994c0701c859a9ce1362df14e18ecfc27e076f
Discussion about the underlying problem:
https://salsa.debian.org/utopia-team/udisks2/merge_requests/2
Fix for the underlying problem:
https://github.com/systemd/systemd/pull/11346/files

**Comment by corbinlc** [comment]
Went ahead and mentioned this issue on the Wiki->FAQ, will add more info there later.
