### ISSUE TITLE
Help - 404 not found

### ISSUE THREAD

**Issue by p4tetoh** [CypherpunkArmory/UserLAnd#1361]
Respectfully sir or ma'am i am concerned with your information. Most basic commands have an error 404 not found ( i.e  curl) 
![Screenshot_20210228-090212_UserLAnd](https://user-images.githubusercontent.com/79684455/109426823-5f930480-79a4-11eb-95a4-05220dacf4af.jpg)
I have deleted and reinstalled the app several times, I have advanced some processes in hopes they would give these basics. They do not. This issue has caused the apps functionality to be zero. Unfortunately I do not have very much experience with Termux , userLAnd, or linux. I only have a Samsung A102U (a10e, Android 10 pie9 {either ARM or ARM7} non root wifi only ) device. Any help and education on Termux , userLAnd , and "Rooting" this device is wonderfull and appreciated. thank you for your time wffort and consideration

**Comment by CRIZEEE** [comment]
Hi, i have the same issue:
Sam galaxy a8 2018 
Android pie 9
Cant update system, cant install any package, seems that the app is outdated but not clear how to update since its not working... 
 
Showing
> e@localhost:~$ sudo apt update
Get:1 http://kali.download/kali kali-rolling InRelease [30.5 kB]
Err:1 http://kali.download/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Fetched 30.5 kB in 3s (11.3 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://kali.download/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
e@localhost:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
e@localhost:~$ sudo apt install wget
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  ca-certificates libpsl5 libssl1.1 openssl
  publicsuffix
The following NEW packages will be installed:
  ca-certificates libpsl5 libssl1.1 openssl
  publicsuffix wget
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 3441 kB of archives.
After this operation, 9447 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://http.kali.org/kali kali-rolling/main arm64 libpsl5 arm64 0.20.2-2
  404  Not Found [IP: 192.99.200.113 80]
Err:2 http://http.kali.org/kali kali-rolling/main arm64 wget arm64 1.20.3-1
  404  Not Found [IP: 192.99.200.113 80]
Err:3 http://http.kali.org/kali kali-rolling/main arm64 libssl1.1 arm64 1.1.1d-2
  404  Not Found [IP: 192.99.200.113 80]
Err:4 http://http.kali.org/kali kali-rolling/main arm64 openssl arm64 1.1.1d-2
  404  Not Found [IP: 192.99.200.113 80]
Err:5 http://http.kali.org/kali kali-rolling/main arm64 ca-certificates all 20190110
  404  Not Found [IP: 192.99.200.113 80]
Err:6 http://http.kali.org/kali kali-rolling/main arm64 publicsuffix all 20190925.1705-1
  404  Not Found [IP: 192.99.200.113 80]
E: Failed to fetch http://http.kali.org/kali/pool/main/libp/libpsl/libpsl5_0.20.2-2_arm64.deb  404  Not Found [IP: 192.99.200.113 80]
E: Failed to fetch http://http.kali.org/kali/pool/main/w/wget/wget_1.20.3-1_arm64.deb  404  Not Found [IP: 192.99.200.113 80]
E: Failed to fetch http://http.kali.org/kali/pool/main/o/openssl/libssl1.1_1.1.1d-2_arm64.deb  404  Not Found [IP: 192.99.200.113 80]
E: Failed to fetch http://http.kali.org/kali/pool/main/o/openssl/openssl_1.1.1d-2_arm64.deb  404  Not Found [IP: 192.99.200.113 80]
E: Failed to fetch http://http.kali.org/kali/pool/main/c/ca-certificates/ca-certificates_20190110_all.deb  404  Not Found [IP: 192.99.200.113 80]
E: Failed to fetch http://http.kali.org/kali/pool/main/p/publicsuffix/publicsuffix_20190925.1705-1_all.deb  404  Not Found [IP: 192.99.200.113 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
e@localhost:~$

>
Any help please?
![20210306_220519](https://user-images.githubusercontent.com/77116463/110219522-63ed7f00-7ec8-11eb-8204-cfbc02a09400.jpg)
![20210306_220553](https://user-images.githubusercontent.com/77116463/110219526-66e86f80-7ec8-11eb-94e3-ae9306db957d.jpg)
![20210306_220621](https://user-images.githubusercontent.com/77116463/110219531-6ea81400-7ec8-11eb-9533-76c3b48c4fa2.jpg)

Thanks!!

**Comment by p4tetoh** [comment]
Termux is awesome

**Comment by onceagainifindmyselfhere** [comment]
If this is kali it really won't matter whether it's termux. They all do
this. You have to cat edit the sources.list and manually add the gpg keys
