### ISSUE TITLE
Back up filesystem?

### ISSUE THREAD

**Issue by lapsio** [CypherpunkArmory/UserLAnd#162]
There were(/are?) many issues with UserLAnd crashes.

Ability to export filesystem backup eg. as .tar or .zip would be nice. Ability to later load such backup after reinstallation of UserLAnd would be even nicer.

**Comment by AdamMatthewLTM** [comment]
@lapsio ,

Thanks for your suggestion. I'll leave this thread open until one is implemented, but for now for clarification's sake for anyone else viewing this reply:

There is currently no method to export a backup of the filesystem in UserLAnd. 

When this changes, I'll make an update to this thread. Thanks again

**Comment by vprusa** [comment]
Hello,
I'm looking into this as well.
Would it be enough to [backup](https://askubuntu.com/questions/225865/copy-files-without-losing-file-folder-permissions) /data/user/0/tech.ula/files/${filesystemId} or are there any other possible problems? I suppose there has to be database record of filesystem in filesystem table. Any ideas what else could cause issues?

**Comment by AdamMatthewLTM** [comment]
@vprusa ,

This is a really late reply, but one issue I have run into before was file path recognition. Doing a manual backup like that is bound to cause a bunch of file not found errors, and I'm still looking into ways to automate the process painlessly. Unfortunately doing so requires a lot of work on the proot extensions, and I can't give a solid ETA on when that would be anywhere close to done. 

Storage and backup will become high priority issues at one point, just not at the moment. So like I said in august, this thread will be updated when I can successfully report we've implemented a backup method, it'll just be a while. Thanks everyone for all your patience and support, we really appreciate it.

**Comment by woodydeck** [comment]
Is there a way to image Android Pie unrooted and restore that to another phone? I haven't had luck with the adb commands, i.e. `$ adb backup -apk -Shared -f /Users/Home/Desktop/backup.ab ` It hangs for me when I try to nip the apks and only makes the same backup as I can do in the GUI.

It was absolutely torture to get R and all dependencies installed, make sure crontab fires on boot, and I still haven't got sendmail to function.

This could be really great because the battery doesn't drain much more than normal and I'm getting RAM heavy R scripts uploading for far cheaper than any VPS. In countries where the power goes out every 5 minutes, using mobile data (cell towers work in power outages for a while) is a godsend. I can buy six phones a year with sim and data for the price of a VPS that I need to do the same.

**Comment by Adityapro9** [comment]
Need kali xfce
