### ISSUE TITLE
48 hours unpaking installing LXDE

### ISSUE THREAD

**Issue by N304LX** [CypherpunkArmory/UserLAnd#170]
Try to install lxde on debian, usually this won't take more than alf hour on other apps, but, for some reasson by now I start the instalation at 8 pm, now are, 9 am and the process still in 53 %, The process now say's "Unpaking PCmanfm"

**Comment by N304LX** [comment]
It's too slow but after wait a lot hours now lxde run so good, now I cant see anything in iceweasel

**Comment by vprusa** [comment]
I am having same issue on Ubuntu, it hangs on unpacking packages. Now 321/513 .. running over night in background 10h+

**Comment by JanuszChmiel** [comment]
May be that this issue is caused by the fact, that data are being stored to 
flash chips inside Tablet or phone. This is The reason why I would strongly 
suggest you t
I suggest you to support external file storage to store file system. Ideal 
situation would be to use USB harddisk with rotating plates, no SD cart. 
Since we can not write directly to Linux file system not to virtual voluem.
o

Odesláno pomocí AquaMail pro Android
https://www.mobisystems.com/aqua-mail

**Comment by vprusa** [comment]
What I do not understand is why is it happening for LXDE dependencies and was not issued sooner elsewhere. Is unpacking slow only for dependencies of LXDE or is apt/dpkg slow for everyone?

@JanuszChmiel using the external file storage may speed things up, but it would be nice to find out solution/workaround less depending on other HW.

Also I am still not convinced that the storage must be the only problem because what I also do not know is how are other restrictions (g.e. ulimits) on devices with this problem set? 

Considering that I/O operations would slow unpacking because there is too many of read/write operations for too many small files would it be possible and/or help to unpack/install dependency into RAM disk first and then copy/store it to storage?

After some googling I have read some mixed signals about installing somewhere else using apt as some [1](https://stackoverflow.com/questions/8567863/how-can-i-change-the-apt-get-install-directory), [2](https://askubuntu.com/questions/404824/how-to-choose-install-location-using-apt-get-install), [3](https://superuser.com/questions/315526/how-to-specify-directory-for-apt-get-to-save-the-packages), [4](https://www.linuxquestions.org/questions/debian-26/install-with-apt-get-in-other-path-386763/) threads follows

**Comment by djangohacked** [comment]
?

Em Seg, 13 de ago de 2018 09:29, Vojtěch Průša <notifications@github.com>
escreveu:

**Comment by vprusa** [comment]
I was at 53% of lxde (overnight) installation using ```apt install lxde -y``` in new session and filesystem at step ```Unpacking lxde-icon-theme``` when my device restarted due to unknown reason... so after restart I started UserLAnd session again and after ssh to it I run ```dpkg --configure -a``` then I read [this](https://unix.stackexchange.com/questions/7238/how-to-make-dpkg-faster) thread and tried to install dependency using ```dpkg --force-unsafe-io -i /var/cache/apt/archives/lxde-icon-theme_0.5.1-2_all.deb``` then ```apt --fix-broken-install```, ```apt install lxde -y```, ```apt upgrade -y``` ... then started XServer XSDL app and run ```export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4712 && startlxde &``` and so far it have not broke. Maybe other icon themes may be installed faster like this as well.. idk.

**Comment by N304LX** [comment]
@AdamMatthewLTM

Sorry for the wait, answers 

1.A list of other packages you have attempted to install and experienced a similar slowdown behavior with during the unpacking stage
Every package have the same issue, The Unpaking stage is too slow 
Until now I have installed:
Lxde
Iceweasel 
Arduino ide
Fritzing 
Build-essential 

Before i have the oportunity to test this app  i Work with Linux deploy, and the time in my dispsotive (Sgs7 edge exinos) Works too fast, i observe the problem is more severe on packages with graphical content in the libs or complements the process its ok(this response the point 2)

**Comment by Herzogs** [comment]
Good morning, I have the same problem when I try to install I3wm in my Debian Filesystem more precisely "Adwaita Icon Theme" when I run "sudo apt-get install xorg lightdm i3-wm i3status suckless-tools"

**Comment by N304LX** [comment]
The compilation of programs it's slow too, last nigth try to compile node. Js with make program, it starts 10:00 pm the task over at 08:00 am, this time, monitoring the cpu of the dispositive (Sgs7 octacore) on Linux deploy ussing make - j4(the j4 prefix i'ts for use of 4 cores) the cpu uses the 8 cores at 80% (in the more hig medition) with 76°c, on UserLAnd, uses 6 cores with values from 3%-92% with 45°c, The comparission with Linux deploy its just for reference

**Comment by AdamMatthewLTM** [comment]
Update to this issue:

Yes I can confirm that unpacking lxde is taking an inordinate amount of time. This issue has already been flagged as high priority (and the sd card implementation is under consideration still), but I will be attempting to diagnose why exactly this is taking so long in the first place. My apologies to everyone affected by this, hopefully I can find out what's going wrong in the next few days.
-Adam

**Comment by vprusa** [comment]
May proot's path translation be the cause as mentioned [here](https://github.com/proot-me/PRoot/issues/124)?

**Comment by corbinlc** [comment]
I can confirm that this is related to our latest PRoot changes (is totally my fault).  It is not related to path translation, but that is interesting...thanks @vprusa .  I think I know the cause as well, I am writing a large array to the tracee's memory space in the fake_id0 extension of proot as part of a work around for a different issue.  It turns out that this was totally unnecessary.  I am going to modify the code to eliminate the bogus memory write and see if it helps.  I am pretty confident it will.

**Comment by ashutoshmaurya1122** [comment]
Same thing with xfce4 ubuntu.It take long time but can not unpack humanities-icon theme,thus unable to install xfce4.

**Comment by corbinlc** [comment]
A new version of proot has been released.  Once your app pulls that in, this issue if fixed.  I can get lxde installed and running in less than 30min on a pixel now.

**Comment by JakeHL** [comment]
Hi, I'm still getting this issue - freshly installed UserLAnd from the play store, is this an up to date version?

**Comment by JanuszChmiel** [comment]
Please if you want to install LXDE and other big applications, do not 
power your device off to suspend mode by pressing power button for short 
time. In other cases, build in power management of Android will allocate 
very less CPU resources to Userland. And process of unpacking packages 
become very slow. It is not internal bug of Userland, it is build in 
power management techniques of Android kernel and other Android 
devicesubsystem. Since many users require so its device will work many 
hours for their battery. Disabling save battery power inside battery 
setting inside Android settings do not help.
And this behaviour will persists also for code written in C language, 
not only for Java or Kotlin code. So to overcome this, try to have your 
device turned on till The installation of LXDE will not be finished.

**Comment by corbinlc** [comment]
@JakeHL you should have an up to date app.  Is it really taking 48hrs+ to install lxde (i normally just do lxde-core)? There was a specific issues that has been solved that was causing it to take 48hrs+ on a device and that issue was solved.  It now takes me < 30min to install `lxde-core`

**Comment by corbinlc** [comment]
If it really is that bad, can you try leaving it in the foreground and see how long it takes and also tell us what version of Android you are dealing with and what device you are using?

**Comment by JakeHL** [comment]
Not quite at 48 hours, but almost 4 hours now. It's been left on the foreground the whole time. I'm on Oreo with the Huawei P20 Pro.

**Comment by JakeHL** [comment]
Unfortunately it’s too slow for me to be useful – guess I chose the wrong phone 😊
