### ISSUE TITLE
I need to access Userland file system from other Linux distro to make changes with no need to relay on SSH client

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#180]
Dear specialists,
Even Connect bot can provide information from console, it is not usable for editing files, adding some texts to specific files from clipboard. So as A visually impaired user I see The only one solution. It is possible to modify file system which have been created by Userland and its components by using other Linux distro? If yes, which kernel module do I have to load to access The file system content from Linux distro which support standard virtual consoles and screen reader? The aim of my attempt is to configure Userland to work with Gnome and Orca on future and with Pulse audio sound server. The next problem, I can not locate Userland file system data file from Windows computer while browsing The phone memory. I can even use Windows drivers for mounting EXT 2 file systems and newer, but I do not know, if Userland uses some file format which is usable with those tools for mounting and editing. Thank you very much.

**Comment by AdamMatthewLTM** [comment]
@JanuszChmiel ,

My apologies for the delayed response. I am having a little difficulty understanding your question. Please tell me if my understanding is correct:

* You want to know how to access the UserLAnd filesystem from another linux device but without having to ssh to the Android device
* You also want to know how to do the same with a windows device
* You would like to know if it is possible to modify the default filesystems (debian and ubuntu) provided by the app

Please tell me if these questions are the right ones so that I may answer them correctly. 

Thank you for your patience,
-Adam

**Comment by AdamMatthewLTM** [comment]
@JanuszChmiel ,

To the best of my knowledge you should be able to copy data from the userland file directories by mounting your android device in windows or linux normally. To actually mount the filesystem is something else entirely and I'm not sure if you can do it the way you are suggesting. If you want to modify files inside userland however that is possible to do manually inside userland or through android studio's file explorer. 

Please let me know if this answers your question,
-Adam
