### ISSUE TITLE
Unable to modify resolution

### ISSUE THREAD

**Issue by zaoqi** [CypherpunkArmory/UserLAnd#215]

**Comment by corbinlc** [comment]
can you modify the .vnc/config file?

**Comment by zaoqi** [comment]
It does not exist and I can not modify geometry by UserLAnd

**Comment by JohnWang1023** [comment]
you can edit the /support/StartVNCServerStep2.sh and add the -geometry argument to the tightvncserver.

**Comment by ibrado** [comment]
Or edit/create /home/user/.vncrc with e.g.

```
$geometry = "2160x1080";
```

**Comment by AdamMatthewLTM** [comment]
@zaoqi ,

Can you please elaborate regarding device specifics and state if this is still an issue for you and exactly what errors you are running into when attempting to edit this file? I have not had any problems editing my screen resolution before. If this is no longer an issue, I will go ahead and close this thread within the next couple of days. 

Thanks for your time and patience,
-Adam

**Comment by X-m7** [comment]
I don't have the .vnc/config file either, I tried creating one and adding geometry=1280x720, no effect. Creating the .vncrc file as @ibrado suggested does work though.

**Comment by AdamMatthewLTM** [comment]
Because there is a workaround provided by @ibrado , and I haven't received specific device and case details, I am going to go ahead and close this thread. If anyone here feels it should remain open, please let me know your reasoning and I will go ahead and re-open it. 

Thank you for your time and consideration,
-Adam
