### ISSUE TITLE
Cannot utime: Permission denied

### ISSUE THREAD

**Issue by fafriat** [CypherpunkArmory/UserLAnd#234]
Hi,
Thanks for your project.

System installation is ok (debian & ubuntu) but when trying to install something like :
sudo apt install wget

I got a lot of exception :
dpkg: error processing archive /tmp/apt-dpkg-install-Tl5JFf/4-publicsuffix_20180223.1310-1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
tar: ./conffiles: Cannot utime: Permission denied
tar: ./control: Cannot utime: Permission denied
tar: ./md5sums: Cannot utime: Permission denied
tar: Exiting with failure status due to previous errors
dpkg-deb: error: tar subprocess returned error exit status 2
dpkg: error processing archive /tmp/apt-dpkg-install-Tl5JFf/5-wget_1.19.4-1ubuntu2_arm64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/apt-dpkg-install-Tl5JFf/0-libssl1.1_1.1.0g-2ubuntu4_arm64.deb
 /tmp/apt-dpkg-install-Tl5JFf/1-openssl_1.1.0g-2ubuntu4_arm64.deb
 /tmp/apt-dpkg-install-Tl5JFf/2-ca-certificates_20180409_all.deb
 /tmp/apt-dpkg-install-Tl5JFf/3-libpsl5_0.19.1-5build1_arm64.deb
 /tmp/apt-dpkg-install-Tl5JFf/4-publicsuffix_20180223.1310-1_all.deb
 /tmp/apt-dpkg-install-Tl5JFf/5-wget_1.19.4-1ubuntu2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Device Information:
Device: TV box based on RK3288
Android Version: 7.1

Thanks for your help...

**Comment by AdamMatthewLTM** [comment]
@fafriat ,

Thank you for your post. The utime permissions errors look like a proot problem, but I am not running into them and I am running Android 7.0 - I have successfully installed wget on my device. I'll go ahead and mark this thread as medium priority and see what still might be causing permissions errors because this shouldn't happen. 

I know this was posted 2 days ago, but @fafriat would you please attempt to install the package once more and let me know if the errors still persist on the off chance some update was delayed?

Thank you for your time and patience in these matters,
-Adam

**Comment by fafriat** [comment]
Hi, I retried again on same board (uninstall + install) and got same problem.
I tried with another board with android 7.1.2 and got the same problem. Maybe same issue as other issue "tar: bin/npx: Cannot utime: Operation not permitted"...

**Comment by josephworks** [comment]
Did you try with sudo

**Comment by AdamMatthewLTM** [comment]
@fafriat ,

The utime issues with installations should have been resolved with the latest version of UserLAnd. If they have not and you are still running into this error, please reply to this thread and I'll take a look at it again. 

Thanks,
-Adam
