### ISSUE TITLE
Allow VNC servers other than tightvnc

### ISSUE THREAD

**Issue by tokoro10g** [CypherpunkArmory/UserLAnd#242]
I had a trouble in setting up tigervnc because the app polls for the existence of **tight**vnc process when we start a session. It resulted in hang up.
I solved the problem by replacing `tigervnc` with `vnc` in `/support/isServerInProcTree.sh` to search for any process names with `vnc`.

I couldn't make a patch since I don't know how the files in `/support` are propagated and which repository contains them. Would you make this change?

And I think it would be great if we can define some custom launch scripts on the app.

**Comment by AdamMatthewLTM** [comment]
@tokoro10g ,

My apologies for the late reply. Your suggestion of startup scripts seems like a duplicate or at least related to issue #60 . May I recommend that this thread be closed and all discussions moved to issue #60 ? 

Thank you for your time and consideration in these matters,
-Adam

**Comment by ibrado** [comment]
I use tigervnc since it has better support for Qt input methods, but I do have to adjust the scripts every time UserLAnd is updated. The changes are pretty transparent, i.e. it's still possible to shift between VNC servers, so perhapa this might be worth keeping separate..? I'll see if I can come up with a simple PR for consideration...

**Comment by tokoro10g** [comment]
Ok, that was so easy (that I felt I was stupid about opening this issue). PR is now on CypherpunkArmory/UserLAnd-Assets-Support#39. I wait for the approval.
