### ISSUE TITLE
I need to chroot Ubuntu 10.10 ARM compiled image

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#247]
Dear specialists,

I have tried to mount one previously prepared Ubuntu 10.10 ARM .img file with Gnome 2.32.1 so I could run Gnome and may be even Orca from Userland Ubuntu session.
But I Am sad, since mount command do not work, I AM getting unknown error -1 while mounting ubuntu.img.
I have even used options which enable kernel loop modules support. Ubuntu 10.10 can be mounted only by using parted, but when I select it with parted, it is very probably not see by Linux kernel as A sevice when I quit parted.
Here is The desired image file.
https://freefr.dl.sourceforge.net/project/linuxonandroid/Ubuntu/10.10/ubuntuV5-image.zip
Or do you think, that I do not chance to combine new Ubuntu base with older one, 
Any help will be very welcomed.

**Comment by AdamMatthewLTM** [comment]
@JanuszChmiel ,

I'm going to close this thread with a recommendation for the following reasons:

At the moment UserLAnd supports 2 filesystems (I am working on the others), debian and ubuntu. Maintaining support for one particular filesystem, let alone multiples, is difficult. Debugging issues with requests for specific FS images may be beyond the scope of UserLAnd at this point in time, unless it becomes a major request or a significant issue pops up that would require us to do so.

In regards to your mounting issue, I am not entirely sure what you are trying to do - mount the image from within UserLAnd while the app is running? If so you are likely to run into many errors. New filesystems are added using a semi-automated build script on the github repos that's modified for each one, if you are interested in the workflow required to get one working go ahead and take a look at the build scripts.

The recommendation I have is here:

Because doing individual support for non-supported versions of filesystems is not within the scope of our issue handling, this thread will be closed - but it can still be commented on by the original poster I believe. So if I have time, I can try to help you with the arm v5 version for ubuntu if you are still interested in getting it working, but it will be a low priority.

If however for any reason you feel this thread /should/ remain open, please state your reasoning in a reply here and if we feel it is appropriate this thread will be re-opened ASAP.

Thanks for your time and patience in these matters,
-Adam
