### ISSUE TITLE
sudo su produces error in Debian session

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#264]
When I type 
sudo su
I Get following error.
 bash: cannot set terminal process group (9684): Inappropriate ioctl for device  
 bash: no job control in this shell                                              
 root@localhost:/home/user
So I get root rights. May be, that this bug is not remarkable and can be safely ignored. But I rater report it.
I Am using official Userland from Google Play, I have started The Debian session after 1 2 hours, so auto update algorithm downloaded proot.sh and today, even Prootsupport.so library have been updated. Very well done dear professionals.

**Comment by corbinlc** [comment]
Why do `sudo su`?  Say you want to update your apt repositories....
You can either:
`sudo apt update` 
or
`su`
`apt-update`
but when do you need to throw the two together?

**Comment by corbinlc** [comment]
hmmm... i guess people really do this.  I never do.  Not sure what is wrong, but probably has to do with our use of `nosudo` in place of `sudo`

if you type `which sudo` you will see it points at `/usr/local/bin/sudo` which is not the same as the normal `/usr/bin/sudo` .

**Comment by corbinlc** [comment]
Yes, the error is not fatal.  So that is good at least.

**Comment by AdamMatthewLTM** [comment]
@JanuszChmiel ,

Thanks for your post. This is expected behavior, those warnings can be safely ignored for the time being. As @corbinlc stated they are not fatal and typically people are expected to use sudo instead of operating every command as the superuser. Ultimately it defaults to the same behavior.

Thank you for your time and consideration,
-Adam
