### ISSUE TITLE
Allow other VNC Apps

### ISSUE THREAD

**Issue by kadrim** [CypherpunkArmory/UserLAnd#278]
I am Not to Happy with bVNC.

It would be nice if there was support for other VNC apps like real VNC

**Comment by schoec1** [comment]
Hi @kadrim,  I am using RealVNC (app is called "VNC Viewer" by RealVNC, version 3.4.2.038468) without any issues. All you have to do is install the app separately and configure it to use the vnc server running inside UserLand, i.e. connect to localhost:<x> where <x> is the port number of the vnc server.

**Comment by kadrim** [comment]
Thanks, i forgot to mention that (for others) - i am using it currently the same way.

But it bothers me, that when i startup the session, that it's always redirecting me to the playstore to download bVNC ;-)

So, yes, technically it's working, from the point of user friendliness it's sub-par. A simple solution would be some kind of checkbox, to ignore the missing bVNC app or better yet, detect other (well known) VNC apps like realVNC.

I really like the way it works for SSH which starts up juiceSSH.

Best regards

**Comment by schoec1** [comment]
Ah, ok, got it ... so as a workaround you could use a ssh session and start the vnc server inside it manually instead of using a preconfigured vnc session in UserLAnd. This of course requires to install the vnc and desktop software by yourself, but it's a one time effort. Additional benefit: you can adjust the display resolution when starting the vnc server, e.g. vncserver -geometry 1920x1024; export DISPLAY=localhost:1; startlxde &
Note: When the UserLAnd session is killed and you start vncserver again, it's using the next port number if you don't clean up /tmp/.X11-unix before starting

**Comment by kadrim** [comment]
good point! if used on a regular basis (like with samsung dex or sentio desktop) one should really startup the vnc server himself (or use something like spice).

**Comment by ashutoshmaurya1122** [comment]
You should add other ssh apps also.Connectbot has lot of issue with userland.
