### ISSUE TITLE
A question, where can we find documentation on upcoming features?

### ISSUE THREAD

**Issue by Root-voidX** [CypherpunkArmory/UserLAnd#321]
As the question suggests, is there a place we can see any upcoming features and works regarding Userland? Like for example the recent update brought paid apps. What does that mean? Are modules going to be sold? Does this mean userland will support non-FOSS pakages?

**Comment by corbinlc** [comment]
We were using github projects to make our project tracking open for all to see, but it doesn't have quite enough features.  We can file issues for the big changes we are planning (we have done it some times, but not consistently) which will allow people to see them and comment on them and even help with them.

Right now anything on the apps page, except distributions, requires a payment to unlock that convenience feature.  You can still do the same yourself without paying, by just using `apt-get` .   We are probably going to change this payment strategy to allow options to use these features without payment, but we are just playing with what works best right now.

All of our code is and will be fully open and free as in speech.  Obviously, you can include non FOSS packages by modifying your apt sources.  We won't need to do that for our base image, but we may need to do that for some app to work.  But, as mentioned our work remains open.  

The things we are probably going to charge for are 1) convenience features and 2) cloud services that are coming, where we cannot make they free as in beer because there is a reoccurring cost to us.

**Comment by Root-voidX** [comment]
Great explanation! 
Cleared things up, i will follow the github project page. The cloud service idea would be neat, i assume its something like a compute server? Also maybe make the QOL stuff have a 1 time pay option as well while cloud have the annual fee (to help with reoccurring fees)?
