### ISSUE TITLE
USB not detecting

### ISSUE THREAD

**Issue by mashrin** [CypherpunkArmory/UserLAnd#336]
Hi, I'm running Ubuntu on Android. I'm using an OTG cable to plug in the pendrive.
It's not getting detected.
Can someone please guide me what should I do so that connected devices is detected (pendrive, USB camera, etc)
Also, can the phone camera be used?

**Comment by stackerlon** [comment]
in simple words android does not allow ubuntu to access some hardware the way ubuntu does. You need root permissions for that which is not included in userland app.

**Comment by mirzaatifbaig** [comment]
Then include a root Option.It's not like People who know how to Open an Issue on github doesn't know how to gain root access.But on the other hand Everything there is about this app would go to hell.The number of issues and errors would increase tenfold.I think there is an API for it and an app uses it.Maybe in kitkat that was Quite possible using Pcap Capture which uses OTG wireless adapter to capture network traffic with no root although I am not entirely sure the tools were in proot Environment.

**Comment by linzuzeng** [comment]
Will that be possible to include a gstreamer or something which streams the camera feed on Android side and then use a User-space device driver to mimic the /dev/camera0 on GNU/Linux side

Similar for other devices like bluetooth or USB drives.

**Comment by AdamMatthewLTM** [comment]
@mashrin , and @linzuzeng 

There are some non-support issues for some hardware detection in UserLAnd at the moment, but at the moment I'm looking at bluetooth support since it's the most requested. Camera support is going to be a bit later.

So this original post was auto-detect on USB not working, but this is going to remain an open issue until hardware support is added later. Therefore, for the time being I'm going to ask that this thread remain open as a low-priority enhancement. Like @corbinlc said, if anyone skilled enough wants to try adding support for their hardware, go ahead and leave the comments here to help others out until we can get around to it.

Thanks everyone for your patience and support in these matters, we really appreciate it
-Adam

**Comment by robanderson** [comment]
I have come across UserLAnd though trying to make use of Android TV boxes to run Octoprint to control 3D printers. Some of these devices I have (Rockchip 3229, MXQ 4k) have 4x USB slots and SD Card slots and Quad-core ARM7 processors in a tidy cheap package and would be a great alternative to buying a limited Raspberry Pi device that Octoprint is typically run on. Support for this functionality would be greatly appreciated so the ever growing user base of 3D Printers can join the world of UserLAnd.

**Comment by corbinlc** [comment]
I have added this to #910 .  It is a list of feature requests that probably cannot be solved properly without running as a real root user.  Please follow and comment there.  I am closing this issue.
