### ISSUE TITLE
UserLAnd stuck on filesystem creation on Samsung Galaxy S9+

### ISSUE THREAD

**Issue by Root-voidX** [CypherpunkArmory/UserLAnd#361]
Hello guys, I ran into a new problem. 

My previous filesystems had some issues so I deleted them and completely wiped app data and redownloaded userland. This is what I am running:

UserLand Beta Playstore v1.0.0
Last Update October 17, 2018
Device: Samsung Galaxy S9+ SM845
OS: Android 8.0 running October Security Update

So I went to filesystems and created a new Debian file system, after that I went into sessions and created an SSH session. It downloads the required files and then displays setting up filesystem. I leave it to do that, on the background. Then nothing happens, it doesn't setup anything. Doesn't even launch ConnectBot (I tried setting up a VNC session with bVNC but same issue). If I close the app and open it again, it gets stuck at the same position. Also additionally, the app says its writting to a Proot Debug File, but the file doesn't exist either. 

Any thoughts? 
**-------------------------------------------------------------------------------------------------------------------**
**UPDATE:**

It seems like Userland falls asleep by default when app is switched out or when screen turns off, I kept the screen on and it finally launched into Debian. But a new issue I noticed. I started an Ubuntu Filesystem and it works fine for SSH, but when I try to launch VNC it keeps repeating "Filesystem Setting" message. It doesn't move forward at all, when i close the app and open it again, I can't even access Ubuntu SSH either, the password I created for the session won't work anymore either. Which is weird because Debian install has no issues.

**Comment by AdamMatthewLTM** [comment]
@Root-voidX ,

I have a similar issue I sometimes experienced when the app was trying to write to the proot debug file but actually was not, after trying to install the filesystem assets. Essentially what happened was my phone was not able to pull the assets from GitHub either because of a poor network connection or some other unknown cause.

I have not been able to replicate this issue consistently however, and I'm running the same version of ULA as you are. So I'm going to mark this as high priority and take a look at it ASAP, to see what's causing the assets download failure and the failure to write to the log file.

Please note: I have Not experienced an issue with the app falling asleep while the screen is shut down, regardless of how long I leave the screen turned off for. That seems to be an entirely separate issue and may be device-specific, further investigation is needed.

Please keep this thread open for now, and I'll post updates here as they come along.

Thanks for your time and patience,
-Adam

**Comment by Root-voidX** [comment]
@AdamMatthewLTM

A little update, if i disable the write to debug option in the settings, the application proceeds as normal. Though i did notice atleast on my device that the untaring and setup process does pause if the screen is turned off, but fortunately continues it when the screen is turned on again. The issue here may have to do with writing to a debug file (or something else entirely but as it is for me, disabling debug file solved the issue for me atm). I believe the process never completes because the app cannot find or create a debug file. The verbosity level doesnt change it either. 

Thought?

**Comment by corbinlc** [comment]
@MatthewTighe will be the one to debug this.  He is out for a week, but he should be able to sort this out.  Maybe @luongthomas wants to take a crack at it, at least see if he can reproduce it.  He has a galaxy s9, which might show the same behavior.
