### ISSUE TITLE
How to keep  app-installations running.

### ISSUE THREAD

**Issue by mats1729** [CypherpunkArmory/UserLAnd#377]
Installation of apps may take a long time, and I found that enabling "Keep the screen always on when charging." in the developer settings  keeps the installation going without the battery saving features of phone suspending it or terminating it. Of course, with the charger attached. For good measure I also enabled UserLAnd to run in the background, but I don't know if that is necessary. If this behaviour can be verified by other users, I think that this should be mentioned in the installation instructions. 

Device: Huawei VTR-L29, Android 8.0.0, EMUI 8.0.0

**Comment by AdamMatthewLTM** [comment]
@mats1729 ,

Thank you for your post. I am not sure why you'd be running into this problem, this issue was solved a while ago. Let's go through the basics for debugging to try to eliminate as many variables as possible, if you can just bear with me.

1) Uninstall UserLAnd through your phone's app settings. 
2) Run the android phone optimizer option to delete unecessary files: found in settings, device maintenence
3) Reboot your phone
4) Re-install UserLAnd directly from the play store

After all of those steps are complete, can you please tell me if you're experiencing this issue on both debian and ubuntu, and what packages specifically you are trying to install or if it seems to take too long on any given package?

Thank you for your time and patience in these matters,
-Adam

**Comment by mats1729** [comment]
Thanks Adam for your interest in the issue. Unless "Keep the screen always on when charging." is selected, the phone will suspend installation when I don't use the phone. I can leave it in the evening, and it hasn't finished in the morning. Thus, to keep the installation going, I need to keep the phone active, e.g. by tapping the screen constantly or by logging in every other moment. The suspension sometimes lead to other problems. I might be prompted to run dpkg --configure -a to clean up the installation state. To proceed after that sometimes work and sometimes not, leading to connection lost and connection refused after short while. However, Corbinic indicated that those problem are related to issues with the Huawei kernel.
Debian and Ubuntu are less likely to cause problems than Octave and R (I have mostly tried Octave, though). However, that the installation process is suspended when the phone is not actively used, affects all larger installations. That is, unless the "always on" option is selected and the phone is attached to the charger. In that case, installations proceed without issues, but the kernel related problems will show up afterwards, when running Octave or R.

I have cleared data and reinstalled UserLAnd from Google Play (after rebooting the phone) several times, trying different approaches to install applications in UserLAnd. There is no optimizer option in the dev section, but there is a storage cleaning option in the storage section. However, when UserLAnd is uninstalled, there is nothing left to remove there.

Installation of the UserLAnd app itself works well, regardless of the settings.

Regards,

Mats

**Comment by corbinlc** [comment]
This is a Huawei specific issue.  They aggressively kill background tasks.  Please see this article about tweaking settings to avoid background apps being killed... https://lifehacker.com/how-to-use-the-blacklisted-vlc-app-on-your-huawei-smart-1827898672

Also, I am going to group this issue with the other Huawei issues.  #398 .  So I am going to close this here, but mention it article and issue in #398.
