### ISSUE TITLE
No fstab created.

### ISSUE THREAD

**Issue by arjay195** [CypherpunkArmory/UserLAnd#390]
Describe the bug

No /etc/fstab file.  "UNCONFIGURED FSTAB FOR BASE SYSTEM" message when typing 'cat /etc/fstab'.  mount -a completes without error message.  the file '/etc/mtab' has 38 line entries.

To Reproduce
Type 'cat /etc/fstab

Expected behavior
I hoped to se a fstab I could start from

Device Information

Device:  Galaxy Tab S3
Android Version:  Oreo 8.0.0
UserLAnd Version 1.0
Additional context
Configuration is Ubuntu with Gnome Desktop- Full

**Comment by AdamMatthewLTM** [comment]
@arjay195 ,

Thank you for your post along with all the relevant information. At the moment, the /etc/fstab file is generating that error message output because of the script used to generate that file in the chroot environment - that is not an ubuntu error.

I will be looking into this matter further, and when I can provide technical details I'll go ahead and update this thread. For the time being please leave this open.

As a _possible__ alternative, please take a look here:

https://unix.stackexchange.com/questions/275429/creating-bootable-debian-image-with-debootstrap/473256#473256

That thread goes over the specifics of configuring the debootstrap script so that the /etc/fstab may be edited manually. It is hardly an ideal workaround for our user base, and I have not personally tested to see if it works or not. Please read all documentation and fully understand code before running it on any device.

I apologize for the inconvenience, and we sincerely appreciate your time and understanding in these matters @arjay195 

-Adam

**Comment by corbinlc** [comment]
This is expected behavior.  The file really has the contents `UNCONFIGURED FSTAB FOR BASE SYSTEM` .  It does not have 38 lines (it does have 37 characters though).  Please file issues for anything this prevents you from doing next.
