### ISSUE TITLE
Use Android functions to check for network availability

### ISSUE THREAD

**Issue by licaon-kter** [CypherpunkArmory/UserLAnd#396]
...and not ping https://www.google.com

**Comment by corbinlc** [comment]
Can you provide an explanation of why you are making this request?  That would help our team.

**Comment by AdamMatthewLTM** [comment]
@licaon-kter ,

Thank you for your post. Can you please provide us with your request according to the issue template so that we may better assist you with your request? At the moment this request is ambiguous. Did you mean to ask if there would be included network utility tools inside the filesystems such as ifconfig and wget, or were you more specifically asking for a feature added to the UserLAnd app itself to determine if network connectivity exists?

**Comment by licaon-kter** [comment]
https://github.com/CypherpunkArmory/UserLAnd/blob/2601bee3d92e3d330c655cdb7de2462b3481883a/app/src/main/java/tech/ula/utils/NetworkUtility.kt#L26

Maybe I've misunderstood the code and the app does not try to connect to Google as means to test the network connection?

**Comment by AdamMatthewLTM** [comment]
@licaon-kter ,

Just to be absolutely clear:

Is your suggestion that the UserLAnd app code itself in the NetworkUtility.kt file be changed to utilize a different connectivity testing method rather than the one described in httpsIsAccessible() ?

**Comment by licaon-kter** [comment]
Yes, one that doesn't rely on a certain site being or not reachable. Specially the site of a company known for being in the business of tracking.

**Comment by licaon-kter** [comment]
@luongthomas Changed Google with Microsoft... that's something. :) :) Thanks
