### ISSUE TITLE
Problems with Huawei Devices

### ISSUE THREAD

**Issue by corbinlc** [CypherpunkArmory/UserLAnd#398]
Describe the bug:

This issue is to summarize remaining issues related to Huawei devices.  The more recent Huawei devices don't support PRoot doing POKE_DATA on the tracee.  There is an expensive and ugly workaround in place, that mostly works, but looks like it still isn't perfect.  There are two problems, some things still don't work on Huawei devices, mainly things related to using VNC and GUI based apps, and performance is noticeably impacted on these Huawei devices.  

I am going to be adding more details to this and pointing some existing issues at this, so we can track this problem and the related work in one place.  

I am starting this to satisfy the desire described in #391 in a different way.

**Comment by corbinlc** [comment]
Can people chime in with the specific issues they are having (including step to reproduce), what Huawei device they have and what version of Android it is running?

**Comment by stackerlon** [comment]
The main problem is android O, userland is broken for android O, there is problem connecting with GUI application like vnc and there is also problem connecting with SSH server It always shows host has disconnected after doing "apt-get update" and "apt-get upgrade" as I mentioned in #401 .

**Comment by JanuszChmiel** [comment]
I have read one information here, that Huawei is suffering because of 
wrongimplementation of one Android Kernel procedure or service I Am not 
kernel expert, Pokedata.
I recommend The most advanced developer here if he could get in touch 
with Huawei company. The main problem is, that if this Kernel function 
or procedure Pokedata is not implemented well for Proot, that other 
phone functions are working perfectly,since I have Huawei with ANdroid 
8.1 at home with update from 10 month of this year.
Phone is stable, even intensive use of text to speech engines is working.
Modern Huawei devices have very advanced power managementcontrols,but 
default setup is not set to extra suspended battery mode.
I think that MR Chanpion and other Proot developers for Userland could 
try to discusswith Huawei developers.
I AM afraid, that Pokedata have been implemented with The intention to 
disable users of Proot module to use it for advanced tasks, may be, that 
wrong implementation of this kernel procedure have been The intention of 
Huawei company.

**Comment by Hiwasgehtab** [comment]
I have a huawei p10 plus, vky-L09, running android 8.0.0
I can set up a debian filesystem but cannot get r to run.
Also see
https://github.com/CypherpunkArmory/UserLAnd/issues/405

**Comment by projectextremum** [comment]
In that case, rooting the phone may be the only solution.
What about `termux`? Probably they provide a native R package. GUI is mostly DIY but it works.

**Comment by AuntieE** [comment]
Yesterday, I managed to put xfce4 on an Honor 5C with AnLinux, Termux and bVNC (yes, bVNC). See enclosed screenshot. Because I think that my problem with UserLAnd might be with memory (issue # 423) and lxde which might be bigger, despite the "light" in the name, I'm going to uninstall UserLAnd and bVNC this morning, then reinstall with xfce4 and see what happens. The bottom line is that I would much prefer to use UserLAnd !
![screenshot_20181127-175250](https://user-images.githubusercontent.com/45310194/49140758-67f7c300-f2f5-11e8-9ea9-4a35265441c1.png)

**Comment by AuntieE** [comment]
I have since put xfce4 on my HONOR 5C telephone with UserLAnd and bVNC. It seems that it IS a memory problem.
![screenshot_20181128-114128](https://user-images.githubusercontent.com/45310194/49148490-ccbc1900-f307-11e8-90ac-35eb8d9199be.png)
![screenshot_20181128-114156](https://user-images.githubusercontent.com/45310194/49148500-d34a9080-f307-11e8-9173-c511885d1f67.png)
I am THRILLED 👍

**Comment by corbinlc** [comment]
#378 is also a Huawei device problem

**Comment by corbinlc** [comment]
One of the things that Huawei does differently that will impact many users is it aggressively kills background apps.  This article talks about how VLC Media Player had a similar issue and how you can tweak some settings to help.  https://lifehacker.com/how-to-use-the-blacklisted-vlc-app-on-your-huawei-smart-1827898672

I have not tried those changes myself, but we have run into one other scenario where changing such settings helped a Huawei user.

**Comment by corbinlc** [comment]
Looking at the issue of running graphical programs on Huawei devices again,  I do see one issue in a proot log that I just created.  I have no idea how quickly that will lead to a solution, but at least there is a symptom I can look into.

**Comment by Kymonlucky** [comment]
@corbinlc is there any update about "!IS_IN_SYSENTER(tracee)". Thanks!

**Comment by XeGrox** [comment]
This appears to be fixed in emui 9 as I am able to run xfce after updating to emui 9 from 8.

**Comment by corbinlc** [comment]
This is great news.  I hope all the effected devices get EMUI 9 soon.  They were all fairly recent devices, so I hope so.
Thanks for the update.  I will check whether our Huawei device has an update pending.

**Comment by corbinlc** [comment]
Can people tell me when they are able to get EMUI 9 and also tell me what device they have and whether the update solves issues seen before?  I want to gauge how quickly this is resolved by Huawei, to better determine how much more effort I should put into it.

**Comment by mscion** [comment]
Hi. I've had it running on my Huawei Mate 20 Pro for a day or so now. Seems to connect ok now. I have a couple other Huawei phones I'll try it on and get back to you.

**Comment by mscion** [comment]
Also seems to work ok on Huawei Mate 10. For my 3 Huawei phones I loaded Debian, libreoffice, wxmaxima, and xfce. Thanks!

**Comment by corbinlc** [comment]
We are no longer hearing any issues as most people have been able to move forward to EMUI 9 and no longer have this issue.  As such, I am closing this.  Please file new specific issues for any remaining problems.

**Comment by shigeru-oyama** [comment]
I had the same response at starting Ubuntu at OUKITEL_C35_EEA_V11_17122023, Android 13 as on #505 by Kymonlucky.
I could start Alpine and Debian.
I am very much beginner for Android, I just lose just only two days with your info.
I understood this could be fatal issue at the note here, so I decided to use Debian.
Thank you for your info.
