### ISSUE TITLE
how to install octave package

### ISSUE THREAD

**Issue by rindj** [CypherpunkArmory/UserLAnd#402]
I installed the package 'symbolic' in octave command window, but when I try to load the package get a not found message.

**Comment by stackerlon** [comment]
What error are you getting? had the package installation completed without any errors?

**Comment by stackerlon** [comment]
What version of ocatve is installed? Newer versions of octave give "symbols undefined" message as 'symbolic' package has not been maintained for years. My advice is to switch to [maxima](http://maxima.sourceforge.net) it is new.

**Comment by rindj** [comment]
I'm using the default octave that loads with install of userland. (I'm on Android 7)  I'll try installing maxima instead of symbolic.

Thanks for the response.
________________________________

**Comment by corbinlc** [comment]
I have successfully used the symbolic package in the past.  I will try it again.

**Comment by corbinlc** [comment]
We have already installed the octave-symbolic package into a debian filesystem [for you](https://github.com/CypherpunkArmory/UserLAnd-Assets-Support/blob/staging/apps/octave/octave.sh), when you launch octave by just clicking the octave app.  So, for me this is all that is needed...
```
pkg load symbolic
syms x
A = sin(x/2)
```
If that works you will see that A is a symbolic equation as opposed to a numeric value.  Please provide what errors you see and even a screen shot, because this appears to work fine in general.

**Comment by corbinlc** [comment]
Ok, so if you are launching from the octave app, you can simply do the commands provided in my previous reply.  If you are installing it and using it manually, you need to first do `sudo apt-get install octave-symbolic` and then do what I recommended within octave.  

For me, this fully solves the issues in both scenarios.  As such, I am closing this issue.  If you are still having an issue, please clarify how what you are doing is different than what I am doing and we can repoen this.
