### ISSUE TITLE
Can't create any App

### ISSUE THREAD

**Issue by Proxtx** [CypherpunkArmory/UserLAnd#416]
I can't start Ubuntu Debian Firefox…There is an Error: "Extracting: Exec: Failed to execute command [../suppor…"

**Comment by corbinlc** [comment]
We are going to need more info.  The template you should have seen, should have asked your what device type you have and what version of android you a running.  In general, UserLAnd works, so we need more info from you.

**Comment by Thor54122** [comment]
Android 8, Second Account, Xiaomi Mi A1, Android One, Beta, It dosen't works on the primary Account untill i installed beta

**Comment by MatthewTighe** [comment]
A PRoot debug log would also be helpful. You can turn debug logging on in the settings menu and then retrieve the log from `/sdcard/PRoot_Debug_Log.txt` or `/mnt/sdcard/PRoot_Debug_Log.txt` of your Android filesystem and not the filesystem you're installing through UserLAnd. Note that this will pretty severely worsen performance.

**Comment by Thor54122** [comment]
Yes but it hadn't workt untill i installed the beta

Am 30.11.2018 06:24 schrieb "corbinlc" <notifications@github.com>:

Oh, that is the issue...it is that you are running this on your second
account. Our app doesn't work on anything but the first account. I haven't
debugged it yet, but it is almost certainly caused by a hardcoded
/data/data path. Does this work on your primary account? I have heard this
issue elsewhere and we should fix it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CypherpunkArmory/UserLAnd/issues/416#issuecomment-443095150>,
or mute the thread

**Comment by corbinlc** [comment]
We now support running in a 2nd account.  This should work now.

**Comment by Proxtx** [comment]
Thank you IT IS WORKING

corbinlc <notifications@github.com> schrieb am Do., 20. Juni 2019, 19:18:
