### ISSUE TITLE
I  get  this   error  when  running  Firefox.

### ISSUE THREAD

**Issue by windy003** [CypherpunkArmory/UserLAnd#433]
It  said  dpkg  was  interrupted.

**Comment by corbinlc** [comment]
Did it provide an error message telling you to run `dpkg --configure -a` manually?  If so, please click the Debian app instead of the Firefox app and, when you connect to it, please run that command.  If that succeeds, please go back and try to run Firefox again.  Note that when you are switching which apps you are running, you need to long press on the running app and stop it before starting a new one.
