### ISSUE TITLE
I have a bunch of problems

### ISSUE THREAD

**Issue by foodmaher** [CypherpunkArmory/UserLAnd#467]
Hello friends 😘 ...

I have a bunch of problems that I suffer from either in Termux or Userland and I also inquired about some other stuff

WARNING: I used a translator to write this article because I do not speak English and am in the process of learning it 😀😀  ...

1. How do I play audio on Termux or Userland ?

2. Why do not all the desktops work on them ?

3. I have problems with the system such as loss of some files due to the erasure of the dpkg info file and also the appearance of errors during the installation of some packages such as Mate desktop on Termux
?
4. Why not all logon interfaces such as lightdm work on both when running by vnc or xsdl ?

5. I suffer from a problem in the Mac-like software bar such as the plank or docky application. The animation does not appear on the Mate interface and on Xfce4 the animation appears. I can show a black background covering half the screen and write to me on the terminal. I do not do what the problem is. dbus or what ?

Regarding the sound I wrote a comment in advance on a post here an hour ago but nobody answered me because the subject is closed and it is related to the sound. I also read it because it explains the problems that faced me in playing the sound and thank you ...
{
I have done everything I mentioned and did not work, it shows me a mistake [E: [pulseaudio] main.c: Too many arguments.]
I do not know what is the reason for this error and the sound does not work

But I do not know if you run the sound over the following command, [export PULSE_SERVER=tcp:127.0.0.1:4712] but it does not work if the xsdl application becomes in the background of the flag I used for Termux and works on Userland also, but Userland is relatively obsolete on the Termux on my phone,

I have used a compiler to reply and can contain errors in sentences that carry me a bit 😀😀
}
Thank you ...

**Comment by foodmaher** [comment]
I have another query about running Wine on one of these applications, Termux or Userland because when I run an exe program for a 32bit kernel or another kernel the application does not work with me and I have a bad exe file I do not know why I need an auxiliary program like exagear but this is not free

**Comment by corbinlc** [comment]
What device do you have and what version of Android are you running?

**Comment by foodmaher** [comment]
@corbinlc ,
Please answer me .... 😟😩

**Comment by corbinlc** [comment]
Couple of things first...
A) Please file separate issues, when you have multiple problems, unless you think they are the same root cause.
B) I will only comment on UserLAnd, as I have hardly used Termux and am not a developer on that project.  Please direct Termux questions to the Termux team.

As for your questions...

1) I honestly have not tried to use sound.  It is not something we officially support.  We have heard that some users have got this working, but are not yet focussed on this feature and have not even confirmed this works.
2) I only used lxde and xfce4.  Those both work well for me, except on newer Huawei devices.  I am not sure why other ones fail.  Having a larger memory footprint is a really good guess, but I haven't tried.
3) Is this question only about Termux?  If so, please see B) above.  If the first part of the question is about UserLAnd, please tell me more.  I am not sure what problem you are talking about or how I could replicate it.
4) No idea right now.  Please file a separate issue that specifically spells out this problem.  
5) Not sure.  Please file a separate issue for this.

**Comment by foodmaher** [comment]
@corbinlc ,

Ok, thank you, my friend, I hope that I did not bother you because of the many problems I have collected in one sual. I am new to Github. I do not know how to inquire about Shi or even raise a work designed for Linux. I will go to learn it from Youtube before asking about Shi next time. 😘😘😘

I will close the subject .....

**Comment by corbinlc** [comment]
No worries.  I simply wanted to instruct you in the best way to file issues and hence get them resolved. 
 Please do come back and file issues in the future.
