### ISSUE TITLE
App crashed when using with the terminal included with the app.

### ISSUE THREAD

**Issue by sr13579** [CypherpunkArmory/UserLAnd#493]
The app crashed everytime I try to open with the internal terminal emulator.

**Comment by MatthewTighe** [comment]
Please update your issue to follow the issue template or we will close the issue within 3 business days.

**Comment by corbinlc** [comment]
We can not help people without more info.  We provide a suggested template when people file an issue that help us gather some particularly pertinent info.  Since we have been unable to get that info from you in the last week (more than the warned 3 days) we are closing this.  If this issue persists and you want to help everyone out, please open a new issue following the provided template.
