### ISSUE TITLE
Include security advisory

### ISSUE THREAD

**Issue by k3an3** [CypherpunkArmory/UserLAnd#50]
I noticed that the app automatically configures SSH or VNC to listen on the phone's network interface. Malicious users on the phone's WiFi network or potentially cell network could connect to the services using the default, weak credentials, and potentially cause harm to the user's UserLAnd session or possibly pivot to the host device's files.

The app should include safer defaults (e.g. bind to localhost only unless manually specified) or _at least_ warn the user about what they are doing.

**Comment by corbinlc** [comment]
The first step in our upcoming security sprint will involve not using a default password, but instead having the user provide one.  That will help a LOT.  Some people will want to connect from another device, so we will have to think about how we want to present the choice of only exposing a service locally or remote as well.

**Comment by lapsio** [comment]
You can set up dropbear to listen on 127.0.0.1 only. People can set up their own second instance or reconfigure it up to their personal taste if they want.

I have question regarding security though: I just locked root and user accounts with `passwd -l root ; passwd -l user` is it enough just like on normal linux? Or there are some quirks related to fact that it's proot so that it'd be better to delete user account whatsoever?

**Comment by AdamMatthewLTM** [comment]
I'm closing this thread for the following reason:

The current version of UserLAnd (.0.5.1) is implementing a changeable password and new security features as of the time of this writing. If anyone feels this thread should remain open for any reason, please let me know with your reasoning and I will go ahead and re-open it ASAP. 

Thanks for your time and patience,
-Adam
