### ISSUE TITLE
Feature Request- Home screen shortcuts for apps on userland

### ISSUE THREAD

**Issue by stackerlon** [CypherpunkArmory/UserLAnd#520]
Home screen shortcut would be a nice thing to get on userland.

**Comment by MatthewTighe** [comment]
Please update your issue to follow the feature request issue template or your issue will be removed within 3 business days.

**Comment by stackerlon** [comment]
@MatthewTighe how? i really don't use github often.

**Comment by MatthewTighe** [comment]
Leave the headers (start with #) and fill in details below them for the following.

# Describe the problem your feature request solves.
A clear and concise description of what the problem is. 

Ex. I'm always frustrated when [...]

# Describe the solution you'd like 
A clear and concise description of what you want to happen.

# Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

# Additional context
Add any other context or screenshots about the feature request here.
