### ISSUE TITLE
Getting No Such App Found

### ISSUE THREAD

**Issue by developerfromjokela** [CypherpunkArmory/UserLAnd#555]
When session is running, and clicking it, it toasts No Such App Found. Using Ubuntu with VNC.

Regards, 
@developerfromjokela

**Comment by Marcus0086** [comment]
Hey @developerfromjokela Can u please provide further details or a screenshot.

**Comment by MatthewTighe** [comment]
@developerfromjokela Please follow the bug report template found [here](https://github.com/CypherpunkArmory/UserLAnd/issues/new?template=bug_report.md&title=Bug+report+-+%5BYOUR+BUG+TITLE%5D). We specifically need reproducible steps in order to make your issue actionable.

This issue will be removed if it isn't updated with more information.

**Comment by developerfromjokela** [comment]
@MatthewTighe 

Hello!

I did research and it was fault of my phone. 
Something is wrong with Android OS on my phone. I will contact to manufacturer, and asking to fix it.

Regards,
@devfromjokela

**Comment by twrightsman** [comment]
@developerfromjokela what was the issue with Android that caused this and were you able to fix it?

I am getting the same error from LineageOS 15.1 when attempting to connect to a VNC session. SSH works fine.

**Comment by developerfromjokela** [comment]
Hello!

I was not able to fix this issue, and I am occurring same issue again when
using ssh.

**Comment by twrightsman** [comment]
For the record, I was able to connect to the VNC session using MultiVNC from F-Droid (localhost:5951).

Maybe UserLAnd is attempting to open the Google Play store to install a VNC app but it errors because I don't have the Google Play store app. Any ideas?

**Comment by developerfromjokela** [comment]
Maybe it's because the Google play, but I have it installed and I am using
Android One so there shouldn't be a problem with that.

**Comment by qroft** [comment]
I would love to confirm that this DOES NOT WORK when you have no VNC client installed.
It seems like UserLAnd checks for an installed VNC app and when it does not find one, it toasts that error.

@developerfromjokela said that with his phone everything works - i suggest that this is so because he, like he mentions it, has Google Play installled.

I have a rooted phone with a custom rom, so there is no Google Play nor Google Play Services or whatever.

[SOLUTION]
What i did was the suggestion from above to simply install MultiVNC and now the toast is gone.
