### ISSUE TITLE
Bug report - [VNC not starting]

### ISSUE THREAD

**Issue by gmkbenjamin** [CypherpunkArmory/UserLAnd#567]
# Describe the bug

App hangs at "Starting service" when trying to start VNC. This worked once or twice but not anymore. Tried reinstalling app. 

# Steps to reproduce the behavior:

Go to Sessions

Click on a VNC session

See error

# Screenshots

# Device Information

Device: Galaxy Note9
Android Version: Android Pie 9
UserLAnd Version 2.2.3
Device is not rooted
Device is running stock ROM

# Additional context

**Comment by MatthewTighe** [comment]
@corbinlc Can you take a look at this log?

**Comment by corbinlc** [comment]
@MatthewTighe there are no errors in the log, but it is spinning searching for the pid file forever.  
@gmkbenjamin What username did you choose?  I see it is looking for `/home/root/.vnc/localhost:51.pid` .  That would imply that you are trying to log in as root and that is not allowed and even if it was allowed, our script would not work with it because `/home/root` is not root's home directory.  
I am pretty sure this is the issue.
@luongthomas can you add to your code that makes sure they are using a good username a check that the username is not root?  I can imagine more than one person has tried to set their username as root.  I still owe you a comprehensive list of usernames that are not allowed, as we have run into something similar before (just not root).
