### ISSUE TITLE
Feature Request - Add Gentoo

### ISSUE THREAD

**Issue by AveViort** [CypherpunkArmory/UserLAnd#579]
Thanks for an amazing app. I use it on Gemini PDA mostly for running Debian (I tried native Debian and didn't like it). However, could you please add Gentoo support? I have managed to run Gentoo Live using qemu, but it required x-session and was not convenient. I also saw Gentoo request in comments for "Add Fedora" issue.

**Comment by corbinlc** [comment]
I am not a gentoo user and I found before on the original GNURoot project that there was a learning curve that was a little higher than I was used to for using that distro.  Do you know how to bootstrap a gentoo chroot for arm?  Or can you find a gentoo image that is very stripped down as a starting point? We may do the work for this, but if you (or anyone) wants this soon, please look here: https://github.com/CypherpunkArmory/UserLAnd/wiki/Adding-a-Distribution

**Comment by EnderNightLord-ChromeBook** [comment]
I'm not working on it at the moment. So you can do it if you want.

**Comment by corbinlc** [comment]
@AveViort that link might not be 100% applicable, because we don't want a PREFIX version that is specifically for Android.  We run the rootfs in a Proot'ed filesystem and so PRoot, is taking care of the PREFIX piece.  Also, it is ok that it is not compiled specifically for android as our system doesn't use the libraries on your android device (like bionic) or the android dynamic loader.  Probably, a more standard rootfs for say a raspberry pi or whatever would be more appropriate.

**Comment by EnderNightLord-ChromeBook** [comment]
Gentoo is very hard to use and build yourself. 

but arm has just a stage 3 without a kernel.
so with some luck we could get it working!

here is some links I found:

https://wiki.gentoo.org/wiki/Chroot

https://www.gentoo.org/downloads/#arm

**Comment by corbinlc** [comment]
To clean things up, I am going to steer all new distro requests to this new feature request #581
