### ISSUE TITLE
The software name should be changed.

### ISSUE THREAD

**Issue by kenneth-Q** [CypherpunkArmory/UserLAnd#65]
The software name UserLAnd is confused with userland display interface. This is not searchable by google and other engine. It may be change to userdocker or so on.
Thanks.

**Comment by AdamMatthewLTM** [comment]
@kenneth-Q , 

Thank you for your suggestion. At the moment the developer team has indicated they wish to maintain the app name UserLAnd citing aesthetic reasons. The hope is that once we come out of beta and our user base grows, we will be the top result in search engines for 'UserLAnd'. 

Because this is not a request for a feature implementation, may I please request that this issue be closed within the next 3 days?

Thank you for your time,
-Adam

**Comment by bet** [comment]
As far as I can tell, search engines ignore alphabetic case.

UserLAnd is exactly the same as userland, and won't find this.
