### ISSUE TITLE
W: Some index files failed to download. They have been ignored, or old ones used instead.

### ISSUE THREAD

**Issue by akilgb** [CypherpunkArmory/UserLAnd#665]
I have tried reinstall the app then I'd tried install different distribution (Debian, Ubuntu) but every single time it's the same error
I have tried it on a LG stylus 3 (Android 7.1) and a LG g stylus alpha (Android 8.1)

e free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Welcome to Debian in UserLAnd!
kev@localhost:~$ sudo apt update
Err:1 http://deb.debian.org/debian stable InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/stable/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stable-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
kev@localhost:~$

I had ask for help on a similar tread but in there some one said me this was not the same issue that's why I have opened this.
Pd: Sorry for my English

**Comment by JasonsDoomGitHub** [comment]
By reinstalling, do you mean to say you were already using userland. Because if that's the case try deleting the apps stored data in the app info section in your devices settings. And see if that works. 
Question are you using Userland in a different language because it could just be that there is a issue or a bug related to packages that support international languages. Idk just a suggestion. Hope u do find a solution because this is an Extraordinary opportunity for android users to use there smartphones as more than a phone. Best of luck 
Yours truly 
-jasonsdoom

**Comment by MatthewTighe** [comment]
This issue is out of date. If you are still experiencing this problem please reopen it.
