### ISSUE TITLE
Feature Request - JavaFX

### ISSUE THREAD

**Issue by foodmaher** [CypherpunkArmory/UserLAnd#744]
# Describe the problem your feature request solves.
The JavaFX library is not available on Arch Linux.

# Describe the solution you'd like 
The JavaFX library is exclusively for Arch Linux. It is the only Linux distribution that supports the GLX or OepnGL libraries that I need to view and create 3D models and create them with the JavaFX library

# Describe alternatives you've considered
There are no alternatives because other Linux distributions do not support the OpenGL library I need as I mentioned earlier (unless there is a way to run OpenGL on Debian or Ubuntu).

Please add any other context or screenshots you think might help us resolve your issue.
N/A

**Comment by corbinlc** [comment]
I am not seeing an arm package for that.  I think if you could find and arm package for it, then using it would be fairly straight forward.  

If you do find a repository that has what you need, you can manually download and install it or add the repo to `/etc/pacman.conf`

How about using openjfx instead?  It looks like there is a Debian package for that (https://packages.debian.org/stretch/openjfx).  That is not arch linux, but at least it means it can be compiled for arm.  

I have no idea if that helps.  

All that said, I am going to close this issue, since I don't think there is a problem with UserLAnd here.

**Comment by foodmaher** [comment]
@corbinlc The problem is that other distributions (except Arch Linux) do not support the GLX or OpenGL that I need to do some animations, whether it's on Java or Python or any other programming language, which makes me use Arch Linux
