### ISSUE TITLE
Bug report - userland does not start without working network

### ISSUE THREAD

**Issue by pferdefreund** [CypherpunkArmory/UserLAnd#753]
# Describe the bug

Since last update of UserLand it does not start without having a working network-connection. The last update was 2 days ago from google-playstore. I use userland often when going to work with railroad and there i have no working network. So i can't start Userland in the train and work with it.

# Steps to reproduce the behavior:

1 I updated userland from google playstore.
2 i stopped networking on my samsung A5(6) because i went to train.
3 i started userland and it brings an error that neworking is missing.
4 when i hat neworking again it starts without any problems and works fine.
5 When i let it running after i started it with networking and i stop networking without stopping userland, it works fine too. My problem is, that i can only start it with a working network-connection.

# Screenshots

# Device Information
Samsung A5 (6) with Android 7.
  
UserLAnd Version 2.5.3
Device is not rooted and runs Android 7.
I tried, to clear the cache of the app and i tryed clear all support files but the problem exists further.
Please excuse my bad engish. I come from Germany and learned it about 45 years ago.
Greetings from Germany
Klaus Schaefer

**Comment by pferdefreund** [comment]
# Describe the bug
Userland does not start without a working network-connection

# Steps to reproduce the behavior:
1 I updated userland from google playstore.
2 i stopped networking on my samsung A5(6) because i went to train.
3 i started userland and it brings an error that neworking is missing.
4 when i hat neworking again it starts without any problems and works fine.
5 When i let it running after i started it with networking and i stop networking without stopping userland, it works fine too. My problem is, that i can only start it with a working network-connection.


# Screenshots
Sorry - not availabele

# Device Information
Samsung A5(6) 
Android Version: 7.0  
UserLAnd Version 2.5.3
device is not rooted.  
device is not running LineageOS 

The problem appeared with the last update from google playstore

**Comment by MatthewTighe** [comment]
I'll look into this. Can you post the error that is shown? As far as I know, it should only error if it hasn't cached information about assets previously. I would have thought that running it on a network once (with the latest update) would fix this problem.

**Comment by pferdefreund** [comment]
it brings up the message UserLand has entered an illegal state could not reach remote host while creating download requirements. Make sure...
It wants network for starting. I started it 3 to 4 times but when i close network it does not start again . Only when networking is up it starts without errors.

**Comment by CodeJoule** [comment]
I am having this problem too. When I click on a session, it crashes once it says "fetching assets". I have to connect to the internet and retry for it to work. Happens with every session I have, Ubuntu, Arch, Alpine.

**Comment by pferdefreund** [comment]
You tried to clear the cache from the app too ? you tried to use the function clear all support files too ? Nothing helped too ? What host-system do you have. Samsung ? and android-version ?

**Comment by MatthewTighe** [comment]
There are a few scenarios being discussed in this thread that are causing crashes that I'd like to discuss:

1. During the 'fetching assets' step, if asset lists have not been cached and there is no network available, UserLAnd will crash. This was @CodeJoule's original problem.
2. If the list of required assets has been cached or successfully fetched from remote, UserLAnd will move onto the 'downloading assets' step.
3. If UserLAnd requires assets to be downloaded and there is no network availability, UserLAnd will crash.

This means that @pferdefreund has somehow cached the required assets lists but doesn't have the assets themselves downloaded. Crashing in this scenario is desired behavior, because we cannot start sessions without those assets. @pferdefreund, if you used the `Clear All Support Files` option after downloading assets after the latest update, that is what's causing problems. The 'support files' that option refers to are the assets that are required to run sessions. If you try to start a session while you have network connectivity, it will download them again and then you should be okay. **Don't clear the cache or clear support files if you want it to continue working without network connectivity.**

Crashing probably isn't the optimal way to handle these failures, but I had previously been under the impression that it was required in order to collect error logs. I'll be looking into a way to handle these errors more gracefully in the near future.

**Comment by MatthewTighe** [comment]
My mistake. There actually is a step that looks like it would always require network connection. I'll work on a fix for that and get it out soon.

**Comment by pferdefreund** [comment]
This morning i installed the update from playstore Version 2.5.4 and everything works as expected. There is no need for Networking when starting the app. Everything is ok nows Thank you and greetings from Germany.

**Comment by RangerMauve** [comment]
Having this problem. I was trying to use UserLAnd for some development on the plane. 😅

**Comment by corbinlc** [comment]
Please open a new issue as this one has been closed for a while.  When you open the new issue, can you say what specifically does not work without a connection?

**Comment by RangerMauve** [comment]
Whoops I was using an out of date APK. Sorry about that!
