### ISSUE TITLE
Help - [every version of Linux I download is empty]]

### ISSUE THREAD

**Issue by elroeeifrah1111** [CypherpunkArmory/UserLAnd#799]
#I tried
To ask a lot of people- nobody knew
To write a lot of commands like:apt-get install kali-linux-full - nothing worked
#what I see when I'm in linux 
The basic and empty version of Linux (even the browser does not work)
#what I want to accomplish
I want the full version of Linux (the type is not really important)
priority to deepin 15.10

**Comment by corbinlc** [comment]
Please provide more details following the template.  Also, please limit this to just one thing you tried and how it failed.  One quick note, you have to run `sudo apt install` instead of just `apt install`.   If that does not help, and you are willing to provide more info, please reopen this issue after providing that additional info.
