### ISSUE TITLE
KALI error sudo dpkg

### ISSUE THREAD

**Issue by Dujani** [CypherpunkArmory/UserLAnd#821]
DEVIDE: HUAWEI P20 LITE
MODELO: ANE-LX3

Unpacking sudo (1.8.27-1) over (1.8.23-2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-YI4wOh/38-sudo_1.8.27-1_arm64.deb (--unpack):
 unable to open '/etc/sudoers.d/README.dpkg-new': Permission denied
invoke-rc.d: could not determine current runlevel
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.
Preparing to unpack .../39-tcl8.6_8.6.9+dfsg-2_arm64.deb ...
Unpacking tcl8.6 (8.6.9+dfsg-2) over (8.6.8+dfsg-4) ...
Preparing to unpack .../40-xfonts-base_1%3a1.0.5_all.deb ...
Unpacking xfonts-base (1:1.0.5) over (1:1.0.4+nmu1) ...
Preparing to unpack .../41-xterm_344-1_arm64.deb ...
Unpacking xterm (344-1) over (337-1) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-YI4wOh/38-sudo_1.8.27-1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
dujani@localhost:~$SMS

**Comment by corbinlc** [comment]
Please follow the template.  For example, you have not provided what version of android you are running.  There is a known issue with Huawei devices running EMUI 8, but you have not provided enough info for us to know.  I am closing the issue, since you were asked for more info more than a month ago.  Feel free to reopen it, after following the template.
