### ISSUE TITLE
Passwd persistence

### ISSUE THREAD

**Issue by DevelopedLogic** [CypherpunkArmory/UserLAnd#83]
Changing the user password with passwd has no effect.

**Comment by AdamMatthewLTM** [comment]
@DevelopedLogic , 

Thank you for your post. At the moment changing passwords has not been implemented yet but will be in future releases. For now the default password will be 'userland' and will persist across session terminations. 

I will go ahead and flag this as a requested feature implementation, but due to its ubiquity may I recommend that this issue be closed for now? If you feel this should remain open please reply here with a brief reason and I will go ahead and leave it open.

Thanks,
-Adam

**Comment by DevelopedLogic** [comment]
May I recommend it remains open so people see it on the opened issue list, but recommend to users that instead of leaving a comment such as "I agree, please do this!" they simply place a thumbs up on the original comment, unless the users require putting additional detail?

**Comment by iammeat** [comment]
Since we are currently unable to change the default password, can I suggest it is modified to be more secure please?

**Comment by ibrado** [comment]
@iammeat You could use `mkpasswd -m sha512` to generate the replacement password field for `/etc/shadow`.

**Comment by iammeat** [comment]
@ibrado Perfect.  I'll do that.  Thanks 👍
