### ISSUE TITLE
Feature Request - [more support for Gemini PDA]

### ISSUE THREAD

**Issue by salvomic** [CypherpunkArmory/UserLAnd#832]
# 1. Userland: Cannot get FN-keys in Gemini PDA + VNC
Please, allow more support for Gemini PDA users. Userland with Debian is all ok in text mode only but in X (i.e. xfde + VNC) with some keyboard layout (for example Italian) it is not possible to get the symbols to write with **FN+keys** (i.e. "-" with FN-. or ~ with FN+s ...)
# Workaround 
A workaround is to use "virtual keyboard", but it a bit tricky, so better a native support for "Gemini keyboard"
***
# 2. Userland lxde: VNC resolution
**VNC resolution** on Gemini PDA is 2080x but the icon and fonts are so small that we need to pinch over and over...
# Proposal 
Allow user to change resolution with a custom setting or to adapt the resolution to a more visible format suiting Gemini PDA screen resolution.

**Comment by corbinlc** [comment]
Any issue with the vnc client, bVNC, should be filed here: https://github.com/iiordanov/remote-desktop-clients/issues
This will allow the developer of that application to help you.

**Comment by thiagoralves** [comment]
After spending a long time looking for a solution for this I finally found a VNC client that **does** work! If you use Remote Desktop Manager (you can find this app on Play Store) it can indeed pass through the fn keys if you press them with left Shift. So, for example, instead of pressing fn+o for dash, you would press left shift + fn + o. I know, Remote Desktop Manager is a bit overkill to just quickly connect to a VNC server, but it is the only solution I could find that actually works. Before that, I was using Unicode hex codes to insert symbols, like Ctrl+u+"2d" = dash, Ctrl+u+"22" = quotation mark, etc.
