### ISSUE TITLE
Help - [run gui applications from debian]

### ISSUE THREAD

**Issue by fghoussen** [CypherpunkArmory/UserLAnd#876]
Just discovered UserLAnd: got debian installed on my Android tablet. Great !

# Describe the issue you are having.

Ok with ssh: cmd line apps run fine (vi, git,...).
Graphical apps (gedit, gitk, ...) don't: how to get them to work ?

Try installing xorg or xfce even if it's a lot more than what i need: still not working.
Try to run with xsd or vnc and get this error : 
http://androidbridge.blogspot.com/2015/05/error-ldso-object-systemliblibsigchains.html
Found no way to unset PRE_LOAD from UserLAnd

# Describe how your task behaves in a regular linux environment

~>gedit
~>gitk

**Comment by Marcus0086** [comment]
@fghoussen in order to use gui applications you have to install vncserver and a desktop environment.
Use these " apt install tightvncserver lxde" 
After that use command " vncserver :1 -geometry 1920x1080" 
And it will ask for password.
After that "export DISPLAY=:1"
And then "startlxde &"
Now install vnc client from app store and connect it on "localhost::5901" name "any"
You will be promoted to gui session

**Comment by fghoussen** [comment]
@Marcus0086 : works great, thanks !
