### ISSUE TITLE
bash: npm: command not found

### ISSUE THREAD

**Issue by SoumyadeepChatterjee96** [CypherpunkArmory/UserLAnd#878]
# bash: npm: command not found
I installed the nodejs but it is fairly outdated and doesn't come with npm and that has put the whole thing Node-Red on hold and I can't find anything to solve it.
I am running Debian without the GUI on a MSM8916 based Lollipop device.
Even sshd returns with 'sshd re-exec requires execution with an absolute path' and I can't seem to find any documentation whatsoever.
If you need any more i-n-fo please tell me what is it cause seems like i am not getting the template thing correctly.

**Comment by corbinlc** [comment]
@SoumyadeepChatterjee96 can you please follow the template and update this issue.?  When doing so, can you provide what distro you are running.  Lastly, these are very minimal filesystems to start with.  You have to install the packages you want in the normal fashion.  In general, UserLAnd should be easier, because how you install `npm` in UserLAnd is exactly how you install `npm` in a normal install of the same linux distro.  For example, if you want to install `npm` you can just do a normal internet search for "how to install npm in ___" where ___ is Debian/Ubuntu/or whatever distro you are using.

**Comment by SoumyadeepChatterjee96** [comment]
@corbinlc what more info do you need cause I am not able to understand and I am stuck right there for quite a while now. Please help.

**Comment by MatthewTighe** [comment]
What are the exact commands you used to reach the failure point, including the installation steps?

**Comment by corbinlc** [comment]
@SoumyadeepChatterjee96, as @MatthewTighe mentioned, I want to know what you tried command by command and what happened when you ran those commands.  There are a few ways to install `npm` and `node.js` on Debian.  A snap won't work, but even if you remove that choice, there are still a few options and we need to know what you have tried.

**Comment by corbinlc** [comment]
@SoumyadeepChatterjee96 we have not heard back from you.  Please continue the conversation with us, or we cannot help you.

**Comment by corbinlc** [comment]
We have not heard anything back from you.  We are closing this issue.
