### ISSUE TITLE
stop creating a "ConnectBot" group in my SSH client app

### ISSUE THREAD

**Issue by hotaru2k3** [CypherpunkArmory/UserLAnd#89]
when I start a session from the UserLAnd app, it allows me to use any of the apps I have installed that provide SSH client functionality (Termius, JuiceSSH, ConnectBot). I prefer Termius over the others, but if I choose it, I end up with a "ConnectBot" group created containing the "localhost" host. If I delete the group, it gets recreated the next time I tap on the session in the UserLAnd app.

**Comment by MatthewTighe** [comment]
Support for Termius will be considered in the future, as we move into public release. As we don't currently support the application, I'm marking this low priority.

Since they are closed-source, there is no way for me to confirm the cause of this bug. Our app just creates an open-ended ssh intent which can be captured by any app that supports it, as you can see. Nothing about that intent contains information specifically about ConnectBot, so there is nothing we can fix.

**Comment by hotaru2k3** [comment]
after looking at the code, it looks like this is Termius' fault. I've reported the bug to them and will close this issue, since there's nothing to be fixed in UserLAnd.
