### ISSUE TITLE
Bug report - [permission override]

### ISSUE THREAD

**Issue by 011235813213455** [CypherpunkArmory/UserLAnd#919]
Hi

I like your work and meny tools are working. msf5 dont start and if i mod with chmod the permission to set a network device up it crash the whole system :/

Greez n cheerz

**Comment by MatthewTighe** [comment]
We need a full list of commands to run to reproduce this issue to provide any help.

**Comment by 011235813213455** [comment]
sudo su
chmod -x /*
exit

Matthew Tighe <notifications@github.com> schrieb am Mo., 15. Juli 2019,
19:44:

**Comment by corbinlc** [comment]
You are not running as real root and some of the directories that are bound to your filesystem are owned by real root and not the emulated root which you are running as.  So you cannot successfully run `chmod -x /*`  You should be able to `chmod` a specific file that you have created or installed.  I am closing this for now, but please open it again with a more specific example instead of `/*` that you need to get working.
