### ISSUE TITLE
Firefox not rendering

### ISSUE THREAD

**Issue by shcreasey** [CypherpunkArmory/UserLAnd#97]
Firefox is not displaying anything at all.

it appears to be loading the page correctly (tooltips appear when hovering over the page) but not rendering anything.

Galaxy tab S3,
Android v 8.0.0 (security patch level: 1 April 2018)

Any help appreciated :)

**Comment by AdamMatthewLTM** [comment]
@shcreasey ,

My apologies for the late response. This issue was filed in the previous version of UserLAnd (GNURootDebian), so I will link the fix that specifically worked for me as well as another one here:

https://github.com/corbinlc/GNURootDebian/issues/234
https://github.com/corbinlc/GNURootDebian/issues/202

For me, the -first- link (Issue 234) worked perfectly. 

" Set browser.tabs.remote.autostart to false in about:config and restart the browser. It works in iceweasel, which is essentially firefox. "

I had to set browser.tabs.remote.autostart.2 to false personally, so it may be different for you as well.

@shcreasey , if this fixes the issue could you please let me know? Thank you so much,
-Adam

**Comment by shcreasey** [comment]
@AdamMatthewLTM 

Yes it does!!

Thanks.  I initially didn't realise that you had to enter about:config in the address bar to get to the setting you mentioned.

Thanks.
